### ISSUE TITLE
google is not defined

### ISSUE THREAD

**Issue by OyeOvi** [kashifsulaiman/SMIT-Batch-5#2]
getting error..
`Uncaught ReferenceError: google is not defined`

**Comment by waseemmaya** [comment]
insert these two lines in the beginning of your component 
i.e on Line 1.

/* eslint-disable no-undef */
/* global google */

**Comment by OyeOvi** [comment]
I was trying to use Map as a component and was using google in the parent component, solved it.
https://stackoverflow.com/a/53208724/5704816
